<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ch.schlau.pesche</groupId>
    <artifactId>apidocs</artifactId>
    <version>0.9-SNAPSHOT</version>

    <name>apidocs</name>
    <packaging>pom</packaging>

    <modules>
        <module>code-first-openapi-quarkus</module>
        <module>code-first-swagger</module>
        <module>design-first-openapi-generator</module>
        <module>design-first-swagger-quarkus</module>
    </modules>

    <properties>
        <minimum-maven-version>3.6.3</minimum-maven-version>
        <maven.enforcer.plugin.version>3.6.2</maven.enforcer.plugin.version>
        <rewrite.plugin.version>6.21.1</rewrite.plugin.version>
        <rewrite.migrate-java.version>3.19.0</rewrite.migrate-java.version>
        <rewrite.third-party.version>0.29.0</rewrite.third-party.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <!-- run it with `mvn org.openrewrite.maven:rewrite-maven-plugin:run -pl '!.'` -->
                <groupId>org.openrewrite.maven</groupId>
                <artifactId>rewrite-maven-plugin</artifactId>
                <version>${rewrite.plugin.version}</version>
                <configuration>
                    <activeRecipes>
                        <recipe>org.openrewrite.java.migrate.UpgradeToJava25</recipe>
                        <!--<recipe>org.openrewrite.quarkus.MigrateToQuarkus_v3_26_0</recipe>-->
                    </activeRecipes>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.openrewrite.recipe</groupId>
                        <artifactId>rewrite-migrate-java</artifactId>
                        <version>${rewrite.migrate-java.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.openrewrite.recipe</groupId>
                        <artifactId>rewrite-third-party</artifactId>
                        <version>${rewrite.third-party.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>${maven.enforcer.plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <requireMavenVersion>
                                    <version>${minimum-maven-version}</version>
                                </requireMavenVersion>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
