<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ch.schlau.pesche</groupId>
    <artifactId>apidocs</artifactId>
    <version>0.9-SNAPSHOT</version>

    <name>apidocs</name>
    <packaging>pom</packaging>

    <modules>
        <module>code-first-openapi-quarkus</module>
        <module>code-first-swagger</module>
        <module>design-first-openapi-generator</module>
        <module>design-first-swagger-quarkus</module>
    </modules>

    <properties>
        <versions.plugin.version>2.18.0</versions.plugin.version>
        <rewrite.plugin.version>6.6.1</rewrite.plugin.version>
        <rewrite.migrate-java.version>3.7.0</rewrite.migrate-java.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openrewrite.maven</groupId>
                <artifactId>rewrite-maven-plugin</artifactId>
                <version>${rewrite.plugin.version}</version>
                <configuration>
                    <activeRecipes>
                        <recipe>org.openrewrite.java.migrate.UpgradeToJava21</recipe>
                    </activeRecipes>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.openrewrite.recipe</groupId>
                        <artifactId>rewrite-migrate-java</artifactId>
                        <version>${rewrite.migrate-java.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>
