# Swagger/OpenAPI in YAML format
GET http://localhost:8080/openapi

###

# Swagger/OpenAPI in JSON format
GET http://localhost:8080/openapi
Accept: application/json

###

POST http://localhost:8080/api/txproc/pincheck
Content-Type: application/json

{
  "uuid": "abcd-ef01",
  "pinBlock": "magic"
}

###

POST http://localhost:8080/api/txproc/purchase
Content-Type: application/json

{
  "uuid": "abcd-ef02",
  "token": { "token": "42" }
}

###
