# the OpenAPI document is provided as source (design-first), no annotation scan needed
mp.openapi.scan.disable = true

# keep /openapi instead /q/openapi for the time being
# see https://quarkus.io/blog/path-resolution-in-quarkus/
quarkus.http.non-application-root-path=${quarkus.http.root-path}

quarkus.openapi.generator.spec=openapi.yaml
quarkus.openapi.generator.input-base-dir=src/main/resources/META-INF
quarkus.openapi.generator.base-package=ch.schlau.pesche.apidocs.quarkiverse.designfirst.generated.model
