openapi: 3.0.0
info:
  title: txproc-design-first-swagger-openliberty
  version: "0.9"
servers:
  - url: http://localhost:8080
paths:
  /api/txproc/pincheck:
    post:
      summary: Check the pin
      operationId: pinCheck
      requestBody:
        description: PIN Check Request Body
        required: true
        content:
          application/json:
            schema:
              $ref: 'elements.yaml#/components/schemas/PinCheckRequest'
      responses:
        default:
          description: PIN Check Response
          content:
            application/json:
              schema:
                $ref: 'elements.yaml#/components/schemas/PinCheckResponse'
  /api/txproc/purchase:
    post:
      summary: Authorize a Purchase
      operationId: purchase
      requestBody:
        description: Purchase Request Body
        required: true
        content:
          application/json:
            schema:
              $ref: 'elements.yaml#/components/schemas/PurchaseAuthRequest'
      responses:
        default:
          description: Purchase Response
          content:
            application/json:
              schema:
                $ref: 'elements.yaml#/components/schemas/PurchaseAuthResponse'
