# Swagger/OpenAPI in YAML format
GET http://localhost:8080/openapi

###

# Swagger/OpenAPI in JSON format
GET http://localhost:8080/openapi
Accept: application/json

###

POST http://localhost:8080/api/txproc/pincheck
Content-Type: application/json

{
  "uuid": "aaaaaaaa-bbbb-cccc-dddd-012345678901",
  "pan" : "100000000042",
  "pinBlock": "magic"
}

###

POST http://localhost:8080/api/txproc/purchase
Content-Type: application/json

{
  "uuid": "aaaaaaaa-bbbb-cccc-dddd-012345678901",
  "pan": "4244333322221111",
  "emvTags": {
    "84" : "A0000000041010",
    "x9F1A" : "250"
  }
}

###
